#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags
{
	namespace AbilityBlockTag
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
	}
	
	namespace Ability
	{
		namespace CoolDown
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Banana);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Booser);

			namespace Fire
			{
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rocket);
			}
		}

		namespace Action
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emote);
		}
	}
	

	namespace Data
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Duration);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Distance);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Radius);
	}
	
	namespace Event
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bomb_Explode);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gimmick_Collect);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_ReloadReFill);
		namespace Round
		{
			namespace Shop
			{
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inflation);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExtremeDilemma);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gacha);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlashSale);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debt);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RiskPurchase);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OpenRun);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BlackMarket);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrowdFunding);
				
				namespace BlackList
				{
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defence);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chaos);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lobby);
				}
				
				namespace Monopoly
				{
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defence);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chaos);
					PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lobby);
				}
			}
			
		}
		namespace Chaos
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DwarfPotion);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IceFloor);
			
		}
		namespace Melee
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit);
		}
	}
	
	namespace MiniGame
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bomb);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CopsAndRobbers);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Delivery);

		namespace State
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IgnoreBatteryLevel);
		}

		namespace Role
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RedLight_Tagger);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Citizen);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cop);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Robber);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(King);
		}
		
	}
	
	namespace Input
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Drop);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emote);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interact);
	}
	
	namespace State
	{
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReaction_HeadShot);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Posture_Crouching);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dead);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Blind);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Bomb);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stasis);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slowing);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Speed);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stealth);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Charge);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Emoting);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bomb);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InPortal);
		
		namespace Passive
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReflectShield);
		}
		
		namespace Movement
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
		}
		
		namespace Ghost
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invisible);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Revealed);
		}
		namespace Posture
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
		}

		namespace Abyss
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoFire);
		}
	}
	namespace Item
	{
		namespace Passive
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReflectShield);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatManual);
		}
		
	}
	
	namespace Weapon
	{
		namespace Anim
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
		}
		namespace Gun
		{
			namespace Pistol
			{
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pistol);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BombPistol);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbyssPistol);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StunPistol);
			}
			namespace Rifle
			{
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CopsRifle);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WaterGun);
				PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RedLightSniper);
			}
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rocket);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vacuum);
		}
		namespace State
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnEquip);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Overheated);
		}

		namespace EquipType
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Special);
		}
		
		namespace Melee
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knife);
		}
	}
	
	namespace GameplayCue
	{
		namespace Weapon
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Explosion);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitImpact);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Water);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Empty);
		}
		
		namespace Item
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invisibility);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stealth);
		}
		namespace State
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blind);
		}
		namespace Hit
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Wall);
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Confirm);
		}
		namespace MiniGame
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Delivery);
		}
	}

	namespace GameState
	{
		namespace MiniGame
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bomb);
		}
	}
	
	namespace ChaosEvent
	{
		namespace Buff
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
		}

		namespace Debuff
		{
			PTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
		}
	}
	
}

